@url = https://bookish-space-tribble-g9w95q46j64fpvxx-8080.app.github.dev

###

GET {{url}}

###

GET {{url}}/livros

###

GET {{url}}/generos

###

POST {{url}}/generos
Content-Type: application/json

{
    "id": 1,
    "descricao": "Ficção Científica"
}

###

POST {{url}}/livros
Content-Type: application/json

{
    "id": 1,
    "titulo": "Harry Potter",
    "generos": "Fantasia",
    "autores": "J.K. Rowling"
}

###

PUT {{url}}/livros/1
Content-Type: application/json

{
    "id": 1,
    "titulo": "Harry Potter - Edição Ilustrada",
    "generos": "Fantasia",
    "autores": "J.K. Rowling"
}

###

PUT {{url}}/generos/1
Content-Type: application/json

{
    "id": 1,
    "descricao": "Romance"
}

###

POST {{url}}/livros
Content-Type: application/json

{
    "id": 2,
    "titulo": "Do Androids Dream of Electric Sheep?",
    "generos": "Ficção Científica",
    "autores": "Philip K. Dick"
}

###

POST {{url}}/generos
Content-Type: application/json

{
    "id": 2,
    "descricao": "Ficção Científica"
}

###

GET {{url}}/livros/2

###

GET {{url}}/generos/2

###

DELETE {{url}}/livros/2

###

DELETE {{url}}/generos/2